#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['boost_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='boost_tests',
    use=['gtest', 'boost_includes']
)
